media: images
content:
  - name: home
    label: Home Page
    type: file
    path: content/homePage.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text, required: true }
      
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    filename: '{primary}.json'
    fields: 
      - { name: title, label: Title, type: string, required: true }
      - { name: published, label: Published, type: boolean, required: true }
      - { name: description, label: Description, type: string, required: true }
      - { name: date, label: Publish Date, type: date, required: true  }
      - { name: image, label: Image, type: image, required: true }
      - { name: body, label: Body, type: rich-text, required: true }

  - name: postsIndex
    label: PostsIndex
    type: file
    path: content/posts/index.json
    fields: 
      - { name: title, label: Title, type: string, required: true }

  - name: works
    label: Works
    type: file
    path: content/works.json
    fields:
      - { name: title, label: Title, type: string }
      - name: entries
        label: Entries
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: string }
          - { name: icon, label: Icon, type: string }
          - { name: soon, label: Soon, type: boolean }