media: images
content:
  - name: hero
    label: Hero Section
    path: content/hero.json
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: rich-text }
      
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields: 
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }