media: images
content:
  - name: hero
    label: Hero Section
    path: content/hero.json
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: rich-text